name: docker-ci

on: 
  pull_request:

jobs:
  super-linter:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter/slim@v5
        env:
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  golangci:
    name: GO lang CI linter
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3 # https://github.com/marketplace/actions/run-golangci-lint
        with:
          version: v1.43

  docker-build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Dockerimage
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: false
